CREATE DATABASE IF NOT EXISTS picpay;

USE picpay;

CREATE TABLE common_users (
    id BINARY(16) NOT NULL PRIMARY KEY,
    complete_name VARCHAR(150) NOT NULL,
    cpf VARCHAR(20) NOT NULL UNIQUE,
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    balance DECIMAL(19,2)
);

CREATE TABLE shopkeepers (
    id BINARY(16) NOT NULL PRIMARY KEY,
    complete_name VARCHAR(150) NOT NULL,
    cnpj VARCHAR(20) NOT NULL UNIQUE,
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    balance DECIMAL(19,2)
);
